using System;
using System.Collections.Generic;
using System.Text;

namespace OOPSchool.P4.InitialData
{
    public class ProfessionInitialData
    {
        public static class ProfessionInitialData
        {
            public static string DataSeedXml => @"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfProfession xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <Profession>
    <ProfessionId>34</ProfessionId>
    <Text>Cleaner</Text>
    <TextLt>Valytojas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>1</ProfessionId>
    <Text>Engineer</Text>
    <TextLt>Inžinierius</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>2</ProfessionId>
    <Text>Programmer</Text>
    <TextLt>Programuotojas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>3</ProfessionId>
    <Text>Pharmacist</Text>
    <TextLt>Vaistininkas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>4</ProfessionId>
    <Text>Manager</Text>
    <TextLt>Vadybininkas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>5</ProfessionId>
    <Text>Soldier</Text>
    <TextLt>Kareivis</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>6</ProfessionId>
    <Text>Officier</Text>
    <TextLt>Karininkas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>7</ProfessionId>
    <Text>Scientist</Text>
    <TextLt>Mokslininkas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>8</ProfessionId>
    <Text>Doctor</Text>
    <TextLt>Daktaras</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>9</ProfessionId>
    <Text>Coach</Text>
    <TextLt>Treneris</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>10</ProfessionId>
    <Text>Translator</Text>
    <TextLt>Vertėjas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>11</ProfessionId>
    <Text>Cook</Text>
    <TextLt>Virėjas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>13</ProfessionId>
    <Text>Singer</Text>
    <TextLt>Dainininkas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>12</ProfessionId>
    <Text>Artist</Text>
    <TextLt>Menininkas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>14</ProfessionId>
    <Text>Photographer</Text>
    <TextLt>Fotografas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>15</ProfessionId>
    <Text>Model</Text>
    <TextLt>Modelis</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>17</ProfessionId>
    <Text>Lawyer</Text>
    <TextLt>Advokatas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>18</ProfessionId>
    <Text>Judge</Text>
    <TextLt>Teisėjas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>19</ProfessionId>
    <Text>Teacher</Text>
    <TextLt>Mokytojas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>20</ProfessionId>
    <Text>Farmer</Text>
    <TextLt>Ūkinintas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>16</ProfessionId>
    <Text>Lecturer</Text>
    <TextLt>Lektorius</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>21</ProfessionId>
    <Text>Architect</Text>
    <TextLt>Architektas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>22</ProfessionId>
    <Text>Actor</Text>
    <TextLt>Aktorius</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>23</ProfessionId>
    <Text>Accountant</Text>
    <TextLt>Buhalteris</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>24</ProfessionId>
    <Text>Diplomat</Text>
    <TextLt>Diplomatas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>25</ProfessionId>
    <Text>Governor</Text>
    <TextLt>Valdytojas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>26</ProfessionId>
    <Text>Ambassador</Text>
    <TextLt>Ambasadorius</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>27</ProfessionId>
    <Text>Spy</Text>
    <TextLt>Šnipas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>28</ProfessionId>
    <Text>Detective</Text>
    <TextLt>Detektyvas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>29</ProfessionId>
    <Text>Psychologist</Text>
    <TextLt>Psichologas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>30</ProfessionId>
    <Text>Writer</Text>
    <TextLt>Rašytojas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>31</ProfessionId>
    <Text>Archaeologist</Text>
    <TextLt>Archiologas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>32</ProfessionId>
    <Text>Historian</Text>
    <TextLt>Istorikas</TextLt>
  </Profession>
  <Profession>
    <ProfessionId>33</ProfessionId>
    <Text>Housekeeping</Text>
    <TextLt>Ūkvedys</TextLt>
  </Profession>
</ArrayOfProfession>";
        }
    }
}
